import { ColorThemeId, type StoredColorTheme } from "@t3tools/contracts";

/**
 * Baked-in presets (no LLM at runtime). Users can also generate custom themes
 * via the Appearance settings prompt box.
 */
export const BUILTIN_COLOR_THEMES: ReadonlyArray<StoredColorTheme> = [
  {
    id: ColorThemeId.make("builtin:catppuccin-mocha"),
    name: "Catppuccin Mocha",
    appearance: "dark",
    background: "#1e1e2e",
    foreground: "#cdd6f4",
    card: "#181825",
    cardForeground: "#cdd6f4",
    popover: "#181825",
    popoverForeground: "#cdd6f4",
    primary: "#89b4fa",
    primaryForeground: "#1e1e2e",
    secondary: "#313244",
    secondaryForeground: "#cdd6f4",
    muted: "#313244",
    mutedForeground: "#a6adc8",
    accent: "#313244",
    accentForeground: "#cdd6f4",
    destructive: "#f38ba8",
    destructiveForeground: "#1e1e2e",
    border: "#45475a",
    input: "#45475a",
    ring: "#89b4fa",
    info: "#89b4fa",
    infoForeground: "#89b4fa",
    success: "#a6e3a1",
    successForeground: "#a6e3a1",
    warning: "#f9e2af",
    warningForeground: "#f9e2af",
    cursor: "#f5e0dc",
    selectionBackground: "#585b7066",
    ansi: {
      black: "#45475a",
      red: "#f38ba8",
      green: "#a6e3a1",
      yellow: "#f9e2af",
      blue: "#89b4fa",
      magenta: "#f5c2e7",
      cyan: "#94e2d5",
      white: "#bac2de",
      brightBlack: "#585b70",
      brightRed: "#f38ba8",
      brightGreen: "#a6e3a1",
      brightYellow: "#f9e2af",
      brightBlue: "#89b4fa",
      brightMagenta: "#f5c2e7",
      brightCyan: "#94e2d5",
      brightWhite: "#a6adc8",
    },
  },
  {
    id: ColorThemeId.make("builtin:catppuccin-latte"),
    name: "Catppuccin Latte",
    appearance: "light",
    background: "#eff1f5",
    foreground: "#4c4f69",
    card: "#e6e9ef",
    cardForeground: "#4c4f69",
    popover: "#e6e9ef",
    popoverForeground: "#4c4f69",
    primary: "#1e66f5",
    primaryForeground: "#eff1f5",
    secondary: "#ccd0da",
    secondaryForeground: "#4c4f69",
    muted: "#ccd0da",
    mutedForeground: "#6c6f85",
    accent: "#ccd0da",
    accentForeground: "#4c4f69",
    destructive: "#d20f39",
    destructiveForeground: "#eff1f5",
    border: "#bcc0cc",
    input: "#bcc0cc",
    ring: "#1e66f5",
    info: "#1e66f5",
    infoForeground: "#1e66f5",
    success: "#40a02b",
    successForeground: "#40a02b",
    warning: "#df8e1d",
    warningForeground: "#df8e1d",
    cursor: "#dc8a78",
    selectionBackground: "#acb0bf66",
    ansi: {
      black: "#5c5f77",
      red: "#d20f39",
      green: "#40a02b",
      yellow: "#df8e1d",
      blue: "#1e66f5",
      magenta: "#ea76cb",
      cyan: "#179299",
      white: "#acb0bf",
      brightBlack: "#6c6f85",
      brightRed: "#d20f39",
      brightGreen: "#40a02b",
      brightYellow: "#df8e1d",
      brightBlue: "#1e66f5",
      brightMagenta: "#ea76cb",
      brightCyan: "#179299",
      brightWhite: "#bcc0cc",
    },
  },
  {
    id: ColorThemeId.make("builtin:dracula"),
    name: "Dracula",
    appearance: "dark",
    background: "#282a36",
    foreground: "#f8f8f2",
    card: "#21222c",
    cardForeground: "#f8f8f2",
    popover: "#21222c",
    popoverForeground: "#f8f8f2",
    primary: "#bd93f9",
    primaryForeground: "#282a36",
    secondary: "#44475a",
    secondaryForeground: "#f8f8f2",
    muted: "#44475a",
    mutedForeground: "#6272a4",
    accent: "#44475a",
    accentForeground: "#f8f8f2",
    destructive: "#ff5555",
    destructiveForeground: "#f8f8f2",
    border: "#44475a",
    input: "#44475a",
    ring: "#bd93f9",
    info: "#8be9fd",
    infoForeground: "#8be9fd",
    success: "#50fa7b",
    successForeground: "#50fa7b",
    warning: "#f1fa8c",
    warningForeground: "#f1fa8c",
    cursor: "#f8f8f2",
    selectionBackground: "#44475a80",
    ansi: {
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
      brightBlack: "#6272a4",
      brightRed: "#ff6e6e",
      brightGreen: "#69ff94",
      brightYellow: "#ffffa5",
      brightBlue: "#d6acff",
      brightMagenta: "#ff92df",
      brightCyan: "#a4ffff",
      brightWhite: "#ffffff",
    },
  },
  {
    id: ColorThemeId.make("builtin:nord"),
    name: "Nord",
    appearance: "dark",
    background: "#2e3440",
    foreground: "#eceff4",
    card: "#3b4252",
    cardForeground: "#eceff4",
    popover: "#3b4252",
    popoverForeground: "#eceff4",
    primary: "#88c0d0",
    primaryForeground: "#2e3440",
    secondary: "#434c5e",
    secondaryForeground: "#eceff4",
    muted: "#434c5e",
    mutedForeground: "#d8dee9",
    accent: "#434c5e",
    accentForeground: "#eceff4",
    destructive: "#bf616a",
    destructiveForeground: "#eceff4",
    border: "#4c566a",
    input: "#4c566a",
    ring: "#88c0d0",
    info: "#81a1c1",
    infoForeground: "#81a1c1",
    success: "#a3be8c",
    successForeground: "#a3be8c",
    warning: "#ebcb8b",
    warningForeground: "#ebcb8b",
    cursor: "#d8dee9",
    selectionBackground: "#4c566a80",
    ansi: {
      black: "#3b4252",
      red: "#bf616a",
      green: "#a3be8c",
      yellow: "#ebcb8b",
      blue: "#81a1c1",
      magenta: "#b48ead",
      cyan: "#88c0d0",
      white: "#e5e9f0",
      brightBlack: "#4c566a",
      brightRed: "#bf616a",
      brightGreen: "#a3be8c",
      brightYellow: "#ebcb8b",
      brightBlue: "#81a1c1",
      brightMagenta: "#b48ead",
      brightCyan: "#8fbcbb",
      brightWhite: "#eceff4",
    },
  },
  {
    id: ColorThemeId.make("builtin:github-light"),
    name: "GitHub Light",
    appearance: "light",
    background: "#ffffff",
    foreground: "#1f2328",
    card: "#f6f8fa",
    cardForeground: "#1f2328",
    popover: "#ffffff",
    popoverForeground: "#1f2328",
    primary: "#0969da",
    primaryForeground: "#ffffff",
    secondary: "#eaeef2",
    secondaryForeground: "#1f2328",
    muted: "#eaeef2",
    mutedForeground: "#656d76",
    accent: "#eaeef2",
    accentForeground: "#1f2328",
    destructive: "#cf222e",
    destructiveForeground: "#ffffff",
    border: "#d0d7de",
    input: "#d0d7de",
    ring: "#0969da",
    info: "#0969da",
    infoForeground: "#0969da",
    success: "#1a7f37",
    successForeground: "#1a7f37",
    warning: "#9a6700",
    warningForeground: "#9a6700",
    cursor: "#1f2328",
    selectionBackground: "#0969da33",
    ansi: {
      black: "#24292f",
      red: "#cf222e",
      green: "#116329",
      yellow: "#4d2d00",
      blue: "#0969da",
      magenta: "#8250df",
      cyan: "#1b7c83",
      white: "#6e7781",
      brightBlack: "#57606a",
      brightRed: "#a40e26",
      brightGreen: "#1a7f37",
      brightYellow: "#633c01",
      brightBlue: "#218bff",
      brightMagenta: "#a475f9",
      brightCyan: "#3192aa",
      brightWhite: "#8c959f",
    },
  },
];

export function listBuiltinThemesForAppearance(
  appearance: "light" | "dark",
): ReadonlyArray<StoredColorTheme> {
  return BUILTIN_COLOR_THEMES.filter((theme) => theme.appearance === appearance);
}
